version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: mini_erp_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: mini_erp
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: mini_erp_backend
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432/mini_erp
      - JWT_SECRET=supersecretkeyformini_erp_crm_system_2026
      - NODE_ENV=production
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: mini_erp_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
